### ISSUE TITLE
Reasons for not using Jekyll

### ISSUE THREAD

**Issue by rugk** [PrivateBin/privatebin.info-pelican#2]
Really, I am only asking. If Pelican works nicely, I am fine with using it, but I at least want to know why you decided to use Jekyll.

**Comment by elrido** [comment]
Ruby? :expressionless: Python is already installed in my Distro. I'm a reformed ansible user that moved away from chef and puppet. Choose one...

**Comment by rugk** [comment]
AFAIK Ruby does not have to be installed on you're server for Jekyll to work.
In any other way the programming language should make no different if you do not write plugins (which us usually not necessary).

**Comment by elrido** [comment]
No, but on the client where you want to execute it...

Sorry, to be more clear: Installing the jekyll package on my distro will add 65 MiB of stuff to my harddrive. Its not so much about the space, but I don't like to have to install a completely new language/compiler/runtime environment just to be able to use one small tool. For the same reason I try to avoid Java (that said, I even like Java better then Ruby, but thats just my personal preference).
