### ISSUE TITLE
Link to PrivateBin Directory in top bar?

### ISSUE THREAD

**Issue by rugk** [PrivateBin/privatebin.info-pelican#21]
IMHO the PrivateBin directory at the right side is hardly findable – it's not that obvious **and** it is a feature man people may look for, judging they come from some other instance (via the footer link) or may want to find a working instace (with >24h expiration date).
Maybe we could move the link into the header? I'd prefer that…

That link is far more useful/(likely) often clicked than the _Installation guide_ or similar links that are just for devs or server admins or so. That is a link for _all_ users, **and** it shows our new fancy dashboard.

**Also** maybe another discussion would be to deprecate (or remove) the Wiki list _or_ at least add a big link at the top there? Information duplication (in different places) is not good IMHO.

**Comment by elrido** [comment]
Sure, just open a PR and move it from the LINKS to the MENUITEMS, in the order you prefer:
https://github.com/PrivateBin/privatebin.info-pelican/blob/d41baaa143bab6beae9978fd6d9bfa2b3b75fd2f/pelicanconf.py#L30-L45
(the navbar consists of all static pages according to their "Sortorder" parameter in the doc, followed by the MENUITEMS for things that are not generated by pelican)

Idea: Maybe rename it from "Directory" to something like "Find one" or "Instance List"? Or we replace the "Try It Out" button or add another button (I think they are in the template)?

**Comment by rugk** [comment]
Yeah, wanted to discuss it before, will do…

**Comment by rugk** [comment]
> Or we replace the "Try It Out" button or add another button (I think they are in the template)?

I would argue against that, because our own instance should be a test instance for "trying it out". As such, the description there fits IMHO.
