### ISSUE TITLE
Try it out link

### ISSUE THREAD

**Issue by rugk** [PrivateBin/privatebin.info-pelican#4]
Users (and webadmins) should be able to use a public test installation to try PrivateBin out.

The "Try it out" link should be highlighted somehow (many in the navigation, but with another background color).

**Comment by rugk** [comment]
Ahh just saw it actually is there. It is the "new link".
I think this button should just be changed to "Try it out", which makes clear what it does.

**Comment by elrido** [comment]
Awww, you killed the joke of the theme... :open_mouth: :wink:

**Comment by rugk** [comment]
Well... sometimes jokes are confusing and if this is the case that's bad UX. I am very sorry, for your joke. :smile:
