### ISSUE TITLE
No margin-bottom on the link list

### ISSUE THREAD

**Issue by rugk** [PrivateBin/privatebin.info-pelican#5]
There already is enough margin/padding from the other element around it:
![nomarginbottom](https://cloud.githubusercontent.com/assets/11966684/17830700/b9c2ade0-66d3-11e6-9857-b2947a96f982.gif)

**Comment by elrido** [comment]
Please push this upstream. I just use the default bootstrap template.

**Comment by rugk** [comment]
Will have to find the place where to insert this.
That's why I opened this issue for now.

**Comment by kyodev** [comment]
normally, in https://privatebin.info/theme/css/privatebin.css you can put:
```css
.list-group {
    margin-bottom: 0;
}
```
if this help

**Comment by elrido** [comment]
We do know that we could fix that there, but if at all this should be fixed by bootstraps team and not be something that we need to spend our valuable time on to do ourselves and then have to maintain.

**Comment by kyodev** [comment]
voila, I think it is here you can change the ccs, that will supersede the bootstrap-theme-3.3.5.css

**Comment by elrido** [comment]
I am closing this issue to avoid any further confusion and time eaten up while more critical things could be solved. Thank you @kyodev for the contribution and I am very sorry for the time this cost you. :-(

**Comment by kyodev** [comment]
no problems, as you want
