### ISSUE TITLE
Let fork me button link to this repo?

### ISSUE THREAD

**Issue by rugk** [PrivateBin/privatebin.info-pelican#6]
Should not the fork me button link to https://github.com/PrivateBin/privatebin.info-pelican? Currently it links to the PrivateBin repo, but in the sidebar there is already a project link linking to the PrivateBin site.

**Comment by elrido** [comment]
Who would want to fork the Website contents on the project page? Of course it should link to the project. The link in the sidebar is duplicate yes, we could remove it.

**Comment by rugk** [comment]
Yeah, either remove it or change it.
